/*
# Setup

***Run this script in its entirety due to the variables***

Use this template notebook to create a new schema in an existing database. It will also create the required database roles for the new schema.

This notebook contains multiple variables that will need to be set before running.

- database_name: enter the name of the existing database in this variable
  - ex: '' -> 'GOVERNANCE'
- schema_name: enter the name of the new schema in this variable
  - ex: '' -> 'COMMON'
- schema_comment: description of the schema and its purpose
  - ex: '' -> 'Schema used for storing various governance objects, including network policies, masking policies, etc.'
 
Prerequisites:

- Configured Snowflake account
- Sysadmin role
- Securityadmin role
- Existing Snowflake database
*/

/*
database_name = 'MAINTENANCE'
schema_name = 'SIMS_4'
schema_comment = 'Schema for storing maintenance / change data capture details for Sims 4 data.'
*/

/*
# RBAC - Role-Based Access Control

The rest of this template is for establishing RBAC in the schema.

Currently, there are four basic roles defined here for the schema. These are not set in stone and can be modified as-needed.

- Read: read-only access
- Modify: change level access (can insert / update / delete data)
- Build: presentation object creation + read-only access
- Engineer: architect access to the schema that doesn't require granting sysadmin

To set a different suffix for the roles, change the variables in "Set Role Names" below. No action is required if these default values are acceptable.
*/

/*
# this is a calculated variable used later; only change if a different read-only role suffix is needed
read_role_name = 'SIMS_4_READ' <- 'SIMS_4_READ'
modify_role_name = 'SIMS_4_MODIFY' <- 'SIMS_4_MODIFY'
build_role_name = 'SIMS_4_BUILD' <- 'SIMS_4_BUILD'
engineer_role_name = 'SIMS_4_ENGINEER' <- 'SIMS_4_ENGINEER'
*/

-- use sysadmin (owner) to create the schema
USE ROLE SYSADMIN;

-- create the schema
-- managed access means the owner of the schema owns all objects within the schema
CREATE SCHEMA IF NOT EXISTS MAINTENANCE.SIMS_4
    WITH MANAGED ACCESS
    COMMENT = 'Schema for storing maintenance / change data capture details for Sims 4 data.'
;

-- confirm the new schema was created
SHOW SCHEMAS LIKE 'SIMS_4' IN DATABASE MAINTENANCE;

/*
## Read-only Database Role Creation

Build the read database role for the schema.

This role allows read-only access to the schema.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE MAINTENANCE;

-- create database role for read access
CREATE DATABASE ROLE IF NOT EXISTS MAINTENANCE.SIMS_4_READ
    COMMENT = 'Role for read-only access to MAINTENANCE SIMS_4 schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SIMS_4_READ' IN DATABASE MAINTENANCE;

-- allows the role to use the database
GRANT USAGE ON DATABASE MAINTENANCE TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- allows the role to use the schema
GRANT USAGE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- select grants
-- tables
GRANT SELECT ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- dynamic tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- external tables
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- iceberg tables
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- interactive tables
GRANT SELECT ON ALL INTERACTIVE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE INTERACTIVE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- views
GRANT SELECT ON ALL VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- materliazlied views
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- read grants
-- stages
GRANT READ ON ALL STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT READ ON FUTURE STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- usage grants (excluding database & schema grants)
-- file formats
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- functions
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
-- stages
GRANT USAGE ON ALL STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

/*
### Optional Grants for Read-only Role

Uncomment the below to run the optional grants, *if needed*.
*/

/*
GRANT USAGE ON ALL STREAMLITS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- notebooks
GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;

-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_READ;
*/

/*
## Modify Database Role Creation

Build the modify database role for the schema.

This role builds on the Read role and allows for altering data in the schema.

This would be used for users who need to insert, update, or delete data.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE MAINTENANCE;

-- create database role for modify access
CREATE DATABASE ROLE IF NOT EXISTS MAINTENANCE.SIMS_4_MODIFY
    COMMENT = 'Role for modify / insert / update / delete access to MAINTENANCE SIMS_4 schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SIMS_4_MODIFY' IN DATABASE MAINTENANCE;

-- grant read role to modify role
GRANT DATABASE ROLE MAINTENANCE.SIMS_4_READ TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- usage grants
-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
-- sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- insert grants
-- tables
GRANT INSERT ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT INSERT ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
-- iceberg tables
GRANT INSERT ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT INSERT ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- delete grants
-- tables
GRANT DELETE ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT DELETE ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
-- iceberg tables
GRANT DELETE ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT DELETE ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- truncate grants
-- tables
GRANT TRUNCATE ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
-- iceberg tables
GRANT TRUNCATE ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT TRUNCATE ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- read grants
-- stages
--   this is included in the _READ role, but the direct grant is needed for the write grant
GRANT READ ON ALL STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT READ ON FUTURE STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- write grants
-- stages
GRANT WRITE ON ALL STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;
GRANT WRITE ON FUTURE STAGES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY;

/*
## Build Database Role Creation

Build the build database role for the schema.

This role builds on the Read role and allows for creating overlay objects.

This would be used for users who need to create presentation layer objects:
- notebooks
- workspaces
- views
- materialized views
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE MAINTENANCE;

-- create database role for build access
CREATE DATABASE ROLE IF NOT EXISTS MAINTENANCE.SIMS_4_BUILD
    COMMENT = 'Role for build access to MAINTENANCE SIMS_4 schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SIMS_4_BUILD' IN DATABASE MAINTENANCE;

-- grant read role to build role
GRANT DATABASE ROLE MAINTENANCE.SIMS_4_READ TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;

-- usage grants
-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;

-- read grants
-- workspaces
GRANT READ ON ALL WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;
GRANT READ ON FUTURE WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;

-- create grants
-- views
GRANT CREATE VIEW ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;
-- materialized views
GRANT CREATE MATERIALIZED VIEW ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;
-- notebooks
GRANT CREATE NOTEBOOK ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;
-- workspaces
GRANT CREATE WORKSPACE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE MAINTENANCE.SIMS_4_BUILD;

/*
## Engineer Database Role Creation

Build the engineer database role for the schema.

This role builds on the Read and Modify roles and allows for creating schema objects.

This would be used for users who need to create all objects, including:
- artifact repositories
- dynamic tables
- file formats
- functions
- hybrid tables
- iceberg tables
- image repositories
- models
- model monitors
- pipes
- procedures
- semantic views
- sequences
- snapshots
- classification profiles
- classifications
- forecasts
- stages
- streams
- tables
- tags
- tasks
- temporary tables
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE MAINTENANCE;

-- create database role for engineer access
CREATE DATABASE ROLE IF NOT EXISTS MAINTENANCE.SIMS_4_ENGINEER
    COMMENT = 'Role for engineer / architect access to MAINTENANCE SIMS_4 schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SIMS_4_ENGINEER' IN DATABASE MAINTENANCE;

-- grant read role to engineer role
GRANT DATABASE ROLE MAINTENANCE.SIMS_4_READ TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- grant modify role to engineer role
GRANT DATABASE ROLE MAINTENANCE.SIMS_4_MODIFY TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- create grants
-- artifact repositories
GRANT CREATE ARTIFACT REPOSITORY ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- backup sets
GRANT CREATE BACKUP SET ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- dynamic tables
GRANT CREATE DYNAMIC TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- external tables
GRANT CREATE EXTERNAL TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- file formats
GRANT CREATE FILE FORMAT ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- functions
GRANT CREATE FUNCTION ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- hybrid tables
GRANT CREATE HYBRID TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- iceberg tables
GRANT CREATE ICEBERG TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- image repositories
GRANT CREATE IMAGE REPOSITORY ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- models
GRANT CREATE MODEL ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- model monitors
GRANT CREATE MODEL MONITOR ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- pipes
GRANT CREATE PIPE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- procedures
GRANT CREATE PROCEDURE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- semantic views
GRANT CREATE SEMANTIC VIEW ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- sequences
GRANT CREATE SEQUENCE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- snapshots
GRANT CREATE SNAPSHOT ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- classification profiles
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- classifications
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- forecasts
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- stages
GRANT CREATE STAGE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- streams
GRANT CREATE STREAM ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- tables
GRANT CREATE TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- tags
GRANT CREATE TAG ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- tasks
GRANT CREATE TASK ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- temporary tables
GRANT CREATE TEMPORARY TABLE ON SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- monitor grants
-- dynamic tables
GRANT MONITOR ON ALL DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- functions
GRANT MONITOR ON ALL FUNCTIONS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE FUNCTIONS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- iceberg tables
GRANT MONITOR ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- pipes
--GRANT MONITOR ON ALL PIPES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE PIPES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- procedures
GRANT MONITOR ON ALL PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE PROCEDURES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- semantic views
GRANT MONITOR ON ALL SEMANTIC VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT MONITOR ON FUTURE SEMANTIC VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- operate grants
-- dynamic tables
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- pipes
--GRANT OPERATE ON ALL PIPES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT OPERATE ON FUTURE PIPES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- read grants
-- secrets
GRANT READ ON ALL SECRETS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT READ ON FUTURE SECRETS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- git repositories
GRANT READ ON ALL GIT REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT READ ON FUTURE GIT REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- image repositories
GRANT READ ON ALL IMAGE REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT READ ON FUTURE IMAGE REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- rebuild grants
-- tables
GRANT REBUILD ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REBUILD ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- references grants
-- external tables
GRANT REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- iceberg tables
GRANT REFERENCES ON ALL ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE ICEBERG TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- materialized views
GRANT REFERENCES ON ALL MATERIALIZED VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE MATERIALIZED VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- semantic views
GRANT REFERENCES ON ALL SEMANTIC VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE SEMANTIC VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- tables
GRANT REFERENCES ON ALL TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- views
GRANT REFERENCES ON ALL VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT REFERENCES ON FUTURE VIEWS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- usage grants
-- dbt projects
GRANT USAGE ON ALL DBT PROJECTS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT USAGE ON FUTURE DBT PROJECTS IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- write grants
-- image repositories
GRANT WRITE ON ALL IMAGE REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT WRITE ON FUTURE IMAGE REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- workspaces
GRANT WRITE ON ALL WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT WRITE ON FUTURE WORKSPACES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
-- git repositories
GRANT WRITE ON ALL GIT REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;
GRANT WRITE ON FUTURE GIT REPOSITORIES IN SCHEMA MAINTENANCE.SIMS_4 TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE MAINTENANCE.SIMS_4_ENGINEER;

/*
# Results

Confirm all schemas and database roles were created successfully.
*/

USE ROLE SYSADMIN;

SHOW SCHEMAS IN DATABASE MAINTENANCE;

SHOW DATABASE ROLES IN DATABASE MAINTENANCE;
