/*
# Setup

***Run this script in its entirety due to the variables***

Use this template notebook to create a new schema in an existing database. It will also create the required database roles for the new schema.

This notebook contains multiple variables that will need to be set before running.

- database_name: enter the name of the existing database in this variable
  - ex: '' -> 'GOVERNANCE'
- schema_name: enter the name of the new schema in this variable
  - ex: '' -> 'COMMON'
- schema_comment: description of the schema and its purpose
  - ex: '' -> 'Schema used for storing various governance objects, including network policies, masking policies, etc.'
 
Prerequisites:

- Configured Snowflake account
- Sysadmin role
- Securityadmin role
- Existing Snowflake database
*/

/*
database_name = 'PRESENTATION'
schema_name = 'STARDEW_VALLEY'
schema_comment = 'Schema for storing presentation layer objects for Stardew Valley data.'
*/

/*
# RBAC - Role-Based Access Control

The rest of this template is for establishing RBAC in the schema.

Currently, there are four basic roles defined here for the schema. These are not set in stone and can be modified as-needed.

- Read: read-only access
- Modify: change level access (can insert / update / delete data)
- Build: presentation object creation + read-only access
- Engineer: architect access to the schema that doesn't require granting sysadmin

To set a different suffix for the roles, change the variables in "Set Role Names" below. No action is required if these default values are acceptable.
*/

/*
# this is a calculated variable used later; only change if a different read-only role suffix is needed
read_role_name = 'STARDEW_VALLEY_READ' <- 'STARDEW_VALLEY_READ'
modify_role_name = 'STARDEW_VALLEY_MODIFY' <- 'STARDEW_VALLEY_MODIFY'
build_role_name = 'STARDEW_VALLEY_BUILD' <- 'STARDEW_VALLEY_BUILD'
engineer_role_name = 'STARDEW_VALLEY_ENGINEER' <- 'STARDEW_VALLEY_ENGINEER'
*/

-- use sysadmin (owner) to create the schema
USE ROLE SYSADMIN;

-- create the schema
-- managed access means the owner of the schema owns all objects within the schema
CREATE SCHEMA IF NOT EXISTS PRESENTATION.STARDEW_VALLEY
    WITH MANAGED ACCESS
    COMMENT = 'Schema for storing presentation layer objects for Stardew Valley data.'
;

-- confirm the new schema was created
SHOW SCHEMAS LIKE 'STARDEW_VALLEY' IN DATABASE PRESENTATION;

/*
## Read-only Database Role Creation

Build the read database role for the schema.

This role allows read-only access to the schema.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE PRESENTATION;

-- create database role for read access
CREATE DATABASE ROLE IF NOT EXISTS PRESENTATION.STARDEW_VALLEY_READ
    COMMENT = 'Role for read-only access to PRESENTATION STARDEW_VALLEY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'STARDEW_VALLEY_READ' IN DATABASE PRESENTATION;

-- allows the role to use the database
GRANT USAGE ON DATABASE PRESENTATION TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- allows the role to use the schema
GRANT USAGE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- select grants
-- tables
GRANT SELECT ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- dynamic tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- external tables
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- iceberg tables
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- interactive tables
GRANT SELECT ON ALL INTERACTIVE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE INTERACTIVE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- views
GRANT SELECT ON ALL VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- materliazlied views
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- read grants
-- stages
GRANT READ ON ALL STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT READ ON FUTURE STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- usage grants (excluding database & schema grants)
-- file formats
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- functions
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
-- stages
GRANT USAGE ON ALL STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

/*
### Optional Grants for Read-only Role

Uncomment the below to run the optional grants, *if needed*.
*/

/*
GRANT USAGE ON ALL STREAMLITS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- notebooks
GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;

-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ;
*/

/*
## Modify Database Role Creation

Build the modify database role for the schema.

This role builds on the Read role and allows for altering data in the schema.

This would be used for users who need to insert, update, or delete data.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE PRESENTATION;

-- create database role for modify access
CREATE DATABASE ROLE IF NOT EXISTS PRESENTATION.STARDEW_VALLEY_MODIFY
    COMMENT = 'Role for modify / insert / update / delete access to PRESENTATION STARDEW_VALLEY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'STARDEW_VALLEY_MODIFY' IN DATABASE PRESENTATION;

-- grant read role to modify role
GRANT DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- usage grants
-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
-- sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- insert grants
-- tables
GRANT INSERT ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT INSERT ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
-- iceberg tables
GRANT INSERT ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT INSERT ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- delete grants
-- tables
GRANT DELETE ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT DELETE ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
-- iceberg tables
GRANT DELETE ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT DELETE ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- truncate grants
-- tables
GRANT TRUNCATE ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
-- iceberg tables
GRANT TRUNCATE ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT TRUNCATE ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- read grants
-- stages
--   this is included in the _READ role, but the direct grant is needed for the write grant
GRANT READ ON ALL STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT READ ON FUTURE STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- write grants
-- stages
GRANT WRITE ON ALL STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;
GRANT WRITE ON FUTURE STAGES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY;

/*
## Build Database Role Creation

Build the build database role for the schema.

This role builds on the Read role and allows for creating overlay objects.

This would be used for users who need to create presentation layer objects:
- notebooks
- workspaces
- views
- materialized views
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE PRESENTATION;

-- create database role for build access
CREATE DATABASE ROLE IF NOT EXISTS PRESENTATION.STARDEW_VALLEY_BUILD
    COMMENT = 'Role for build access to PRESENTATION STARDEW_VALLEY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'STARDEW_VALLEY_BUILD' IN DATABASE PRESENTATION;

-- grant read role to build role
GRANT DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;

-- usage grants
-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;

-- read grants
-- workspaces
GRANT READ ON ALL WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;
GRANT READ ON FUTURE WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;

-- create grants
-- views
GRANT CREATE VIEW ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;
-- materialized views
GRANT CREATE MATERIALIZED VIEW ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;
-- notebooks
GRANT CREATE NOTEBOOK ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;
-- workspaces
GRANT CREATE WORKSPACE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_BUILD;

/*
## Engineer Database Role Creation

Build the engineer database role for the schema.

This role builds on the Read and Modify roles and allows for creating schema objects.

This would be used for users who need to create all objects, including:
- artifact repositories
- dynamic tables
- file formats
- functions
- hybrid tables
- iceberg tables
- image repositories
- models
- model monitors
- pipes
- procedures
- semantic views
- sequences
- snapshots
- classification profiles
- classifications
- forecasts
- stages
- streams
- tables
- tags
- tasks
- temporary tables
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE PRESENTATION;

-- create database role for engineer access
CREATE DATABASE ROLE IF NOT EXISTS PRESENTATION.STARDEW_VALLEY_ENGINEER
    COMMENT = 'Role for engineer / architect access to PRESENTATION STARDEW_VALLEY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'STARDEW_VALLEY_ENGINEER' IN DATABASE PRESENTATION;

-- grant read role to engineer role
GRANT DATABASE ROLE PRESENTATION.STARDEW_VALLEY_READ TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- grant modify role to engineer role
GRANT DATABASE ROLE PRESENTATION.STARDEW_VALLEY_MODIFY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- create grants
-- artifact repositories
GRANT CREATE ARTIFACT REPOSITORY ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- backup sets
GRANT CREATE BACKUP SET ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- dynamic tables
GRANT CREATE DYNAMIC TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- external tables
GRANT CREATE EXTERNAL TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- file formats
GRANT CREATE FILE FORMAT ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- functions
GRANT CREATE FUNCTION ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- hybrid tables
GRANT CREATE HYBRID TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- iceberg tables
GRANT CREATE ICEBERG TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- image repositories
GRANT CREATE IMAGE REPOSITORY ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- models
GRANT CREATE MODEL ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- model monitors
GRANT CREATE MODEL MONITOR ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- pipes
GRANT CREATE PIPE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- procedures
GRANT CREATE PROCEDURE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- semantic views
GRANT CREATE SEMANTIC VIEW ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- sequences
GRANT CREATE SEQUENCE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- snapshots
GRANT CREATE SNAPSHOT ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- classification profiles
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- classifications
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- forecasts
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- stages
GRANT CREATE STAGE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- streams
GRANT CREATE STREAM ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- tables
GRANT CREATE TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- tags
GRANT CREATE TAG ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- tasks
GRANT CREATE TASK ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- temporary tables
GRANT CREATE TEMPORARY TABLE ON SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- monitor grants
-- dynamic tables
GRANT MONITOR ON ALL DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- functions
GRANT MONITOR ON ALL FUNCTIONS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE FUNCTIONS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- iceberg tables
GRANT MONITOR ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- pipes
--GRANT MONITOR ON ALL PIPES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE PIPES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- procedures
GRANT MONITOR ON ALL PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE PROCEDURES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- semantic views
GRANT MONITOR ON ALL SEMANTIC VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT MONITOR ON FUTURE SEMANTIC VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- operate grants
-- dynamic tables
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- pipes
--GRANT OPERATE ON ALL PIPES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT OPERATE ON FUTURE PIPES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- read grants
-- secrets
GRANT READ ON ALL SECRETS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT READ ON FUTURE SECRETS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- git repositories
GRANT READ ON ALL GIT REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT READ ON FUTURE GIT REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- image repositories
GRANT READ ON ALL IMAGE REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT READ ON FUTURE IMAGE REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- rebuild grants
-- tables
GRANT REBUILD ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REBUILD ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- references grants
-- external tables
GRANT REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- iceberg tables
GRANT REFERENCES ON ALL ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE ICEBERG TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- materialized views
GRANT REFERENCES ON ALL MATERIALIZED VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE MATERIALIZED VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- semantic views
GRANT REFERENCES ON ALL SEMANTIC VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE SEMANTIC VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- tables
GRANT REFERENCES ON ALL TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- views
GRANT REFERENCES ON ALL VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT REFERENCES ON FUTURE VIEWS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- usage grants
-- dbt projects
GRANT USAGE ON ALL DBT PROJECTS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT USAGE ON FUTURE DBT PROJECTS IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- write grants
-- image repositories
GRANT WRITE ON ALL IMAGE REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT WRITE ON FUTURE IMAGE REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- workspaces
GRANT WRITE ON ALL WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT WRITE ON FUTURE WORKSPACES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
-- git repositories
GRANT WRITE ON ALL GIT REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;
GRANT WRITE ON FUTURE GIT REPOSITORIES IN SCHEMA PRESENTATION.STARDEW_VALLEY TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE PRESENTATION.STARDEW_VALLEY_ENGINEER;

/*
# Results

Confirm all schemas and database roles were created successfully.
*/

USE ROLE SYSADMIN;

SHOW SCHEMAS IN DATABASE PRESENTATION;

SHOW DATABASE ROLES IN DATABASE PRESENTATION;
