USE ROLE ACCOUNTADMIN;

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS WORLD_OF_WARCRAFT_CLIENT_ACCESS
    ALLOWED_NETWORK_RULES = (
        GOVERNANCE.SECURITY.WORLD_OF_WARCRAFT_OUTBOUND
    )
    ALLOWED_AUTHENTICATION_SECRETS = (
        GAMING.WORLD_OF_WARCRAFT.OAUTH_CLIENT
    )
    ENABLED = TRUE
;

GRANT USAGE ON INTEGRATION WORLD_OF_WARCRAFT_CLIENT_ACCESS TO ROLE SYSADMIN;
