USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION WORLD_OF_WARCRAFT_CLIENT_ACCESS
    ALLOWED_NETWORK_RULES = (
        GOVERNANCE.SECURITY.WORLD_OF_WARCRAFT_OUTBOUND
    )
    ALLOWED_AUTHENTICATION_SECRETS = (
        INGESTION.WORLD_OF_WARCRAFT.CLIENT
    )
    ENABLED = TRUE
;

GRANT USAGE ON INTEGRATION WORLD_OF_WARCRAFT_CLIENT_ACCESS TO ROLE SYSADMIN;
