USE ROLE ACCOUNTADMIN;

CREATE SECURITY INTEGRATION IF NOT EXISTS WORLD_OF_WARCRAFT_CLIENT
    TYPE = API_AUTHENTICATION
    AUTH_TYPE = OAUTH2
    ENABLED = TRUE
    OAUTH_TOKEN_ENDPOINT = 'https://oauth.battle.net/token'
    OAUTH_CLIENT_AUTH_METHOD = CLIENT_SECRET_BASIC
    OAUTH_CLIENT_ID = '1eb7808180434960849ebef0038260f5'
    OAUTH_CLIENT_SECRET = 'M7k7k867nzInkHCmVuYIxei5IEdp9xJc'
    OAUTH_GRANT = 'CLIENT_CREDENTIALS'
    COMMENT = 'Security integration for connecting to the World of Warcraft API'
;

SHOW SECURITY INTEGRATIONS LIKE 'WORLD_OF_WARCRAFT_CLIENT';
DESC SECURITY INTEGRATION WORLD_OF_WARCRAFT_CLIENT;

SELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION())
WHERE QUERY_TEXT ILIKE 'CREATE SECURITY INTEGRATION%'
ORDER BY START_TIME DESC
;

GRANT USAGE ON INTEGRATION WORLD_OF_WARCRAFT_CLIENT TO ROLE SYSADMIN;
