USE ROLE SYSADMIN;
USE DATABASE INGESTION;
USE SCHEMA WORLD_OF_WARCRAFT;

CREATE SECRET IF NOT EXISTS INGESTION.WORLD_OF_WARCRAFT.CLIENT
    TYPE = OAUTH2
    API_AUTHENTICATION = WORLD_OF_WARCRAFT_CLIENT
;
