/*
# Setup

***Run this script in its entirety due to the variables***

Use this template notebook to create a new schema in an existing database. It will also create the required database roles for the new schema.

This notebook contains multiple variables that will need to be set before running.

- database_name: enter the name of the existing database in this variable
  - ex: '' -> 'GOVERNANCE'
- schema_name: enter the name of the new schema in this variable
  - ex: '' -> 'COMMON'
- schema_comment: description of the schema and its purpose
  - ex: '' -> 'Schema used for storing various governance objects, including network policies, masking policies, etc.'
 
Prerequisites:

- Configured Snowflake account
- Sysadmin role
- Securityadmin role
- Existing Snowflake database
*/

/*
database_name = 'GOVERNANCE'
schema_name = 'SECURITY'
schema_comment = 'Schema for holding security objects like network rules and policies, masking policies, etc.'
*/

/*
# RBAC - Role-Based Access Control

The rest of this template is for establishing RBAC in the schema.

Currently, there are four basic roles defined here for the schema. These are not set in stone and can be modified as-needed.

- Read: read-only access
- Modify: change level access (can insert / update / delete data)
- Build: presentation object creation + read-only access
- Engineer: architect access to the schema that doesn't require granting sysadmin

To set a different suffix for the roles, change the variables in "Set Role Names" below. No action is required if these default values are acceptable.
*/

/*
# this is a calculated variable used later; only change if a different read-only role suffix is needed
read_role_name = 'SECURITY_READ' <- 'SECURITY_READ'
modify_role_name = 'SECURITY_MODIFY' <- 'SECURITY_MODIFY'
build_role_name = 'SECURITY_BUILD' <- 'SECURITY_BUILD'
engineer_role_name = 'SECURITY_ENGINEER' <- 'SECURITY_ENGINEER'
*/

-- use sysadmin (owner) to create the schema
USE ROLE SYSADMIN;

-- create the schema
-- managed access means the owner of the schema owns all objects within the schema
CREATE SCHEMA IF NOT EXISTS GOVERNANCE.SECURITY
    WITH MANAGED ACCESS
    COMMENT = 'Schema for holding security objects like network rules and policies, masking policies, etc.'
;

-- confirm the new schema was created
SHOW SCHEMAS LIKE 'SECURITY' IN DATABASE GOVERNANCE;

/*
## Read-only Database Role Creation

Build the read database role for the schema.

This role allows read-only access to the schema.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for read access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.SECURITY_READ
    COMMENT = 'Role for read-only access to GOVERNANCE SECURITY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SECURITY_READ' IN DATABASE GOVERNANCE;

-- allows the role to use the database
GRANT USAGE ON DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- allows the role to use the schema
GRANT USAGE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- select grants
-- tables
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- dynamic tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- external tables
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- iceberg tables
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- interactive tables
GRANT SELECT ON ALL INTERACTIVE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE INTERACTIVE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- views
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- materliazlied views
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- read grants
-- stages
GRANT READ ON ALL STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT READ ON FUTURE STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- usage grants (excluding database & schema grants)
-- file formats
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- functions
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
-- stages
GRANT USAGE ON ALL STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

/*
### Optional Grants for Read-only Role

Uncomment the below to run the optional grants, *if needed*.
*/

/*
GRANT USAGE ON ALL STREAMLITS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- notebooks
GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;

-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_READ;
*/

/*
## Modify Database Role Creation

Build the modify database role for the schema.

This role builds on the Read role and allows for altering data in the schema.

This would be used for users who need to insert, update, or delete data.
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for modify access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.SECURITY_MODIFY
    COMMENT = 'Role for modify / insert / update / delete access to GOVERNANCE SECURITY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SECURITY_MODIFY' IN DATABASE GOVERNANCE;

-- grant read role to modify role
GRANT DATABASE ROLE GOVERNANCE.SECURITY_READ TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- usage grants
-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
-- sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- insert grants
-- tables
GRANT INSERT ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT INSERT ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
-- iceberg tables
GRANT INSERT ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT INSERT ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- delete grants
-- tables
GRANT DELETE ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT DELETE ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
-- iceberg tables
GRANT DELETE ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT DELETE ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- truncate grants
-- tables
GRANT TRUNCATE ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
-- iceberg tables
GRANT TRUNCATE ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT TRUNCATE ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- read grants
-- stages
--   this is included in the _READ role, but the direct grant is needed for the write grant
GRANT READ ON ALL STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT READ ON FUTURE STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- write grants
-- stages
GRANT WRITE ON ALL STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;
GRANT WRITE ON FUTURE STAGES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE GOVERNANCE.SECURITY_MODIFY;

/*
## Build Database Role Creation

Build the build database role for the schema.

This role builds on the Read role and allows for creating overlay objects.

This would be used for users who need to create presentation layer objects:
- notebooks
- workspaces
- views
- materialized views
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for build access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.SECURITY_BUILD
    COMMENT = 'Role for build access to GOVERNANCE SECURITY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SECURITY_BUILD' IN DATABASE GOVERNANCE;

-- grant read role to build role
GRANT DATABASE ROLE GOVERNANCE.SECURITY_READ TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;

-- usage grants
-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;

-- read grants
-- workspaces
GRANT READ ON ALL WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;
GRANT READ ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;

-- create grants
-- views
GRANT CREATE VIEW ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;
-- materialized views
GRANT CREATE MATERIALIZED VIEW ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;
-- notebooks
GRANT CREATE NOTEBOOK ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;
-- workspaces
GRANT CREATE WORKSPACE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE GOVERNANCE.SECURITY_BUILD;

/*
## Engineer Database Role Creation

Build the engineer database role for the schema.

This role builds on the Read and Modify roles and allows for creating schema objects.

This would be used for users who need to create all objects, including:
- artifact repositories
- dynamic tables
- file formats
- functions
- hybrid tables
- iceberg tables
- image repositories
- models
- model monitors
- pipes
- procedures
- semantic views
- sequences
- snapshots
- classification profiles
- classifications
- forecasts
- stages
- streams
- tables
- tags
- tasks
- temporary tables
*/

-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;

-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for engineer access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.SECURITY_ENGINEER
    COMMENT = 'Role for engineer / architect access to GOVERNANCE SECURITY schema'
;

-- confirm the database role was created
SHOW DATABASE ROLES LIKE 'SECURITY_ENGINEER' IN DATABASE GOVERNANCE;

-- grant read role to engineer role
GRANT DATABASE ROLE GOVERNANCE.SECURITY_READ TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- grant modify role to engineer role
GRANT DATABASE ROLE GOVERNANCE.SECURITY_MODIFY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- create grants
-- artifact repositories
GRANT CREATE ARTIFACT REPOSITORY ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- backup sets
GRANT CREATE BACKUP SET ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- dynamic tables
GRANT CREATE DYNAMIC TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- external tables
GRANT CREATE EXTERNAL TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- file formats
GRANT CREATE FILE FORMAT ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- functions
GRANT CREATE FUNCTION ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- hybrid tables
GRANT CREATE HYBRID TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- iceberg tables
GRANT CREATE ICEBERG TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- image repositories
GRANT CREATE IMAGE REPOSITORY ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- models
GRANT CREATE MODEL ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- model monitors
GRANT CREATE MODEL MONITOR ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- pipes
GRANT CREATE PIPE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- procedures
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- semantic views
GRANT CREATE SEMANTIC VIEW ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- sequences
GRANT CREATE SEQUENCE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- snapshots
GRANT CREATE SNAPSHOT ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- classification profiles
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- classifications
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- forecasts
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- stages
GRANT CREATE STAGE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- streams
GRANT CREATE STREAM ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- tables
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- tags
GRANT CREATE TAG ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- tasks
GRANT CREATE TASK ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- temporary tables
GRANT CREATE TEMPORARY TABLE ON SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- monitor grants
-- dynamic tables
GRANT MONITOR ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- functions
GRANT MONITOR ON ALL FUNCTIONS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE FUNCTIONS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- iceberg tables
GRANT MONITOR ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- pipes
--GRANT MONITOR ON ALL PIPES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE PIPES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- procedures
GRANT MONITOR ON ALL PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- semantic views
GRANT MONITOR ON ALL SEMANTIC VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT MONITOR ON FUTURE SEMANTIC VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- operate grants
-- dynamic tables
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- pipes
--GRANT OPERATE ON ALL PIPES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT OPERATE ON FUTURE PIPES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- read grants
-- secrets
GRANT READ ON ALL SECRETS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT READ ON FUTURE SECRETS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- git repositories
GRANT READ ON ALL GIT REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT READ ON FUTURE GIT REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- image repositories
GRANT READ ON ALL IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT READ ON FUTURE IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- rebuild grants
-- tables
GRANT REBUILD ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REBUILD ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- references grants
-- external tables
GRANT REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- iceberg tables
GRANT REFERENCES ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- materialized views
GRANT REFERENCES ON ALL MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- semantic views
GRANT REFERENCES ON ALL SEMANTIC VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE SEMANTIC VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- tables
GRANT REFERENCES ON ALL TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- views
GRANT REFERENCES ON ALL VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT REFERENCES ON FUTURE VIEWS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- usage grants
-- dbt projects
GRANT USAGE ON ALL DBT PROJECTS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT USAGE ON FUTURE DBT PROJECTS IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- write grants
-- image repositories
GRANT WRITE ON ALL IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT WRITE ON FUTURE IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- workspaces
GRANT WRITE ON ALL WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT WRITE ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
-- git repositories
GRANT WRITE ON ALL GIT REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;
GRANT WRITE ON FUTURE GIT REPOSITORIES IN SCHEMA GOVERNANCE.SECURITY TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

-- confirm grants
SHOW GRANTS TO DATABASE ROLE GOVERNANCE.SECURITY_ENGINEER;

/*
# Results

Confirm all schemas and database roles were created successfully.
*/

USE ROLE SYSADMIN;

SHOW SCHEMAS IN DATABASE GOVERNANCE;

SHOW DATABASE ROLES IN DATABASE GOVERNANCE;
