USE ROLE SYSADMIN;

USE DATABASE INGESTION;
USE SCHEMA WORLD_OF_WARCRAFT;

CREATE OR REPLACE FUNCTION INGESTION.WORLD_OF_WARCRAFT.API_PROFESSION_INDEX()
    RETURNS VARIANT
    LANGUAGE SQL
AS
$$
    INGESTION.WORLD_OF_WARCRAFT.CALL_CLIENT_API(
        'https://us.api.blizzard.com/data/wow/profession/index',
        'static-us',
        'en_US'
    )
$$
;

SELECT INGESTION.WORLD_OF_WARCRAFT.API_PROFESSION_INDEX();

SELECT
    profession.value:id::NUMBER AS PROFESSION_ID
    ,profession.value:name::VARCHAR AS PROFESSION_NAME
    ,profession.value:key:href::VARCHAR AS PROFESSION_URL
    ,profession.value::VARIANT AS PROFESSION_JSON
FROM TABLE(
    FLATTEN(
        INPUT => INGESTION.WORLD_OF_WARCRAFT.API_PROFESSION_INDEX():professions
    )
) profession
ORDER BY PROFESSION_NAME
;
