USE ROLE SYSADMIN;

USE DATABASE INGESTION;
USE SCHEMA WORLD_OF_WARCRAFT;

CREATE OR REPLACE FUNCTION INGESTION.WORLD_OF_WARCRAFT.BUILD_API_URL(
    REGION VARCHAR
    ,BASE_URL VARCHAR
    ,ENDPOINT_TYPE VARCHAR
    ,ENDPOINT VARCHAR
    ,ENDPOINT_IDENTIFIER VARCHAR
)
    RETURNS VARCHAR
    LANGUAGE SQL
AS
$$
    'https://' ||
    IFNULL(REGION, INGESTION.WORLD_OF_WARCRAFT.GET_API_PART('DEFAULT_REGION')) || '.' ||
    IFNULL(BASE_URL, INGESTION.WORLD_OF_WARCRAFT.GET_API_PART('DEFAULT_BASE_URL')) || '/' ||
    CASE
        WHEN ENDPOINT_TYPE = 'CLIENT' THEN INGESTION.WORLD_OF_WARCRAFT.GET_API_PART('DEFAULT_CLIENT_PREFIX')
        WHEN ENDPOINT_TYPE = 'PROFILE' THEN INGESTION.WORLD_OF_WARCRAFT.GET_API_PART('DEFAULT_PROFILE_PREFIX')
        ELSE ''
    END || '/' ||
    ENDPOINT ||
    IFNULL('/' || ENDPOINT_IDENTIFIER, '')
$$
;

CREATE OR REPLACE FUNCTION INGESTION.WORLD_OF_WARCRAFT.BUILD_API_URL(
    ENDPOINT_TYPE VARCHAR
    ,ENDPOINT VARCHAR
    ,ENDPOINT_IDENTIFIER VARCHAR
)
    RETURNS VARCHAR
    LANGUAGE SQL
AS
$$
    INGESTION.WORLD_OF_WARCRAFT.BUILD_API_URL(
        REGION => NULL,
        BASE_URL => NULL,
        ENDPOINT_TYPE => ENDPOINT_TYPE,
        ENDPOINT => ENDPOINT,
        ENDPOINT_IDENTIFIER => ENDPOINT_IDENTIFIER
    )
$$
;

CREATE OR REPLACE FUNCTION INGESTION.WORLD_OF_WARCRAFT.BUILD_API_URL(
    ENDPOINT_TYPE VARCHAR
    ,ENDPOINT VARCHAR
)
    RETURNS VARCHAR
    LANGUAGE SQL
AS
$$
    INGESTION.WORLD_OF_WARCRAFT.BUILD_API_URL(
        REGION => NULL,
        BASE_URL => NULL,
        ENDPOINT_TYPE => ENDPOINT_TYPE,
        ENDPOINT => ENDPOINT,
        ENDPOINT_IDENTIFIER => NULL
    )
$$
;
