USE ROLE SYSADMIN;

USE DATABASE INGESTION;
USE SCHEMA WORLD_OF_WARCRAFT;

CREATE OR REPLACE FUNCTION GET_API_PART(
    PART_IDENTIFIER VARCHAR
)
    RETURNS VARCHAR
    LANGUAGE SQL
AS
$$
    RETURN CASE
        WHEN PART_IDENTIFIER = 'DEFAULT_REGION' THEN 'us'
        WHEN PART_IDENTIFIER = 'DEFAULT_NAMESPACE' THEN 'static-us'
        WHEN PART_IDENTIFIER = 'DEFAULT_LOCALE' THEN 'en_US'
        WHEN PART_IDENTIFIER = 'DEFAULT_BASE_URL' THEN 'api.blizzard.com'
        WHEN PART_IDENTIFIER = 'DEFAULT_CLIENT_PREFIX' THEN 'data/wow'
        ELSE ''
    END
$$
;
