USE ROLE SYSADMIN;

USE DATABASE INGESTION;
USE SCHEMA WORLD_OF_WARCRAFT;

CREATE OR REPLACE FUNCTION INGESTION.WORLD_OF_WARCRAFT.TEST_API_CLIENT_OAUTH()
    RETURNS BOOLEAN
    LANGUAGE PYTHON
    RUNTIME_VERSION = '3.12'
    HANDLER = 'test_oauth'
    EXTERNAL_ACCESS_INTEGRATIONS = (WORLD_OF_WARCRAFT_CLIENT_ACCESS)
    SECRETS = ('oauth_client' = INGESTION.WORLD_OF_WARCRAFT.OAUTH_CLIENT)
AS
$$

import _snowflake

def test_oauth():
    return bool(_snowflake.get_oauth_access_token('oauth_client'))

$$
;

SELECT TEST_API_CLIENT_OAUTH();
